app:
  all:
    env:
      default:
        message: application.yaml#/app/all/env/default/message --- 5
      dev:
        message: application.yaml#/app/all/env/dev/message --- 5
      prod:
        message: application.yaml#/app/all/env/prod/message --- 5
  myapp:
    env:
      default:
        message: application.yaml#/app/myapp/env/default/message --- 5
      dev:
        message: application.yaml#/app/myapp/env/dev/message --- 5
      prod:
        message: application.yaml#/app/myapp/env/prod/message --- 5
  myapp2:
    env:
      default:
        message: application.yaml#/app/myapp2/env/default/message --- 5
      dev:
        message: application.yaml#/app/myapp2/env/dev/message --- 5
      prod:
        message: application.yaml#/app/myapp2/env/prod/message --- 5
