app:
  myapp:
    env:
      dev:
        message: myapp-dev.yaml#/app/myapp/env/dev/message --- 2
      prod:
        message: myapp-dev.yaml#/app/myapp/env/prod/message --- 2
  myapp2:
    env:
      default:
        message: myapp-dev.yaml#/app/myapp2/env/default/message --- 2
      dev:
        message: myapp-dev.yaml#/app/myapp2/env/dev/message --- 2
      prod:
        message: myapp-dev.yaml#/app/myapp2/env/prod/message --- 2
