app:
  myapp:
    env:
      dev:
        message: myapp-prod.yaml#/app/myapp/env/dev/message --- 4
      prod:
        message: myapp-prod.yaml#/app/myapp/env/prod/message --- 4
  myapp2:
    env:
      default:
        message: myapp-prod.yaml#/app/myapp2/env/default/message --- 4
      dev:
        message: myapp-prod.yaml#/app/myapp2/env/dev/message --- 4
      prod:
        message: myapp-prod.yaml#/app/myapp2/env/prod/message --- 4
