app:
  myapp:
    env:
      dev:
        message: myapp-dev.yaml#/app/myapp/env/dev/message
      prod:
        message: myapp-dev.yaml#/app/myapp/env/prod/message
  myapp2:
    env:
      default:
        message: myapp-dev.yaml#/app/myapp2/env/default/message
      dev:
        message: myapp-dev.yaml#/app/myapp2/env/dev/message
      prod:
        message: myapp-dev.yaml#/app/myapp2/env/prod/message
